/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp;

/**
 *
 * @author Alex
 */

import Business.Business;
import Business.Person.Person;
import Business.Profiles.AcademicAdvisorProfile;
import Business.UserAccounts.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class ManageAcademicAdvisorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAcademicAdvisorJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    AcademicAdvisorProfile selectedAcademicAdvisor;
    
    public ManageAcademicAdvisorJPanel(Business b, JPanel jp) {
        business = b;
        CardSequencePanel = jp;
        initComponents();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAcademicAdvisor = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtAcademicAdvisorID = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        tblAcademicAdvisor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Has Account?"
            }
        ));
        tblAcademicAdvisor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblAcademicAdvisorMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblAcademicAdvisor);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel3.setText("Advisor ID:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Academic Advisors");

        jLabel4.setText("Name:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Manage Academic Advisors");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Back)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAdd)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(btnDelete))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                        .addComponent(txtAcademicAdvisorID, javax.swing.GroupLayout.Alignment.LEADING)))))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(Back)
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAcademicAdvisorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(99, 99, 99))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblAcademicAdvisorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAcademicAdvisorMousePressed
        // Extracts the row (uaser account) in the table that is selected by the user
        int selectedRow = tblAcademicAdvisor.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        String academicadvisorId = tblAcademicAdvisor.getValueAt(selectedRow, 0).toString();

        selectedAcademicAdvisor = business.getAcademicAdvisorDirectory().findAcademicAdvisor(academicadvisorId);

        if (selectedAcademicAdvisor == null) {
            JOptionPane.showMessageDialog(this, "Could not find selected advisor.");
            return;
        }

        Person person = selectedAcademicAdvisor.getPerson();
        txtAcademicAdvisorID.setText(person.getPersonId());
        txtName.setText(person.getFirstName());
    }//GEN-LAST:event_tblAcademicAdvisorMousePressed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String academicadvisorId = txtAcademicAdvisorID.getText().trim();
        String name = txtName.getText().trim();

        if (academicadvisorId.isBlank() || name.isBlank()) {
            JOptionPane.showMessageDialog(this, "Please enter both advisor ID and name.");
            return;
        }

        if (business.getAcademicAdvisorDirectory().findAcademicAdvisor(academicadvisorId) != null) {
            JOptionPane.showMessageDialog(this, "An advisor with this ID already exists.");
            return;
        }

        Person person = business.getPersonDirectory().newPerson(academicadvisorId);
        person.setFirstName(name);

        business.getAcademicAdvisorDirectory().newAcademicAdvisorProfile(person);

        JOptionPane.showMessageDialog(this, "Advisor added successfully.");

        clearFields();
        selectedAcademicAdvisor = null;
        refreshTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (selectedAcademicAdvisor == null) {
            JOptionPane.showMessageDialog(this, "Please select an advisor to delete.");
            return;
        }

        Person person = selectedAcademicAdvisor.getPerson();

        UserAccount account = business.getUserAccountDirectory()
                .findUserAccount(person.getPersonId());

        if (account != null) {
            JOptionPane.showMessageDialog(this,
                    "This advisor already has a user account. Delete the account first.");
            return;
        }

        int result = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete this advisor?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION
        );

        if (result != JOptionPane.YES_OPTION) {
            return;
        }

        business.getAcademicAdvisorDirectory().removeAcademicAdvisorProfile(selectedAcademicAdvisor);
        business.getPersonDirectory().removePerson(person);

        JOptionPane.showMessageDialog(this, "Advisor deleted successfully.");

        clearFields();
        selectedAcademicAdvisor = null;
        refreshTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");
    }//GEN-LAST:event_BackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (selectedAcademicAdvisor == null) {
            JOptionPane.showMessageDialog(this, "Please select an advisor to update.");
            return;
        }

        String academicadvisorId = txtAcademicAdvisorID.getText().trim();
        String name = txtName.getText().trim();

        if (academicadvisorId.isBlank() || name.isBlank()) {
            JOptionPane.showMessageDialog(this, "Please enter both advisor ID and name.");
            return;
        }

        AcademicAdvisorProfile existing = business.getAcademicAdvisorDirectory().findAcademicAdvisor(academicadvisorId);

        if (existing != null && existing != selectedAcademicAdvisor) {
            JOptionPane.showMessageDialog(this, "Another advisor already has this ID.");
            return;
        }

        Person person = selectedAcademicAdvisor.getPerson();
        person.setPersonId(academicadvisorId);
        person.setFirstName(name);

        JOptionPane.showMessageDialog(this, "Advisor updated successfully.");

        clearFields();
        selectedAcademicAdvisor = null;
        refreshTable();
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAcademicAdvisor;
    private javax.swing.JTextField txtAcademicAdvisorID;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblAcademicAdvisor.getModel();
        model.setRowCount(0);

        for (AcademicAdvisorProfile ep : business.getAcademicAdvisorDirectory().getAcademicAdvisorList()) {
            Person person = ep.getPerson();

            UserAccount account = business.getUserAccountDirectory()
                    .findUserAccount(person.getPersonId());

            Object[] row = new Object[3];
            row[0] = person.getPersonId();
            row[1] = person.getFirstName();
            row[2] = account == null ? "No" : "Yes";

            model.addRow(row);
        }
    }
    
    private void clearFields() {
        txtAcademicAdvisorID.setText("");
        txtName.setText("");
    }

}
