/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;
import Business.Person.Person;
import Business.Profiles.StudentProfile;
import Business.Advising.AdvisorRecord;

/**
 *
 * @author abhit
 */
public class ManageStudentProfile extends javax.swing.JPanel {
      private Business.Business business;
      private Business.Profiles.FacultyProfile facultyProfile;
      private javax.swing.JPanel CardSequencePanel;
    /**
     * Creates new form ManageStudentProfile
     */
    public ManageStudentProfile(Business.Business business, Business.Profiles.FacultyProfile facultyProfile, javax.swing.JPanel CardSequencePanel) {
        this.business= business;
        this.facultyProfile = facultyProfile;
        this.CardSequencePanel= CardSequencePanel;
        initComponents();
        populateStudentTable();
        setupTableSelectionListener();
    }
    private void populateStudentTable() {
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    

    model.addColumn("Name");
    model.addColumn("NUID");
    model.addColumn("Email");
    model.addColumn("Department");

    if (business == null || business.getStudentDirectory() == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Student directory is not available.");
        StudentProfileTable.setModel(model);
        return;
    }

    for (StudentProfile sp : business.getStudentDirectory().getStudentList()) {
        if (sp == null || sp.getPerson() == null) {
            continue;
        }

        Person p = sp.getPerson();

        model.addRow(new Object[]{
            safeText(p.getFullName()),
            safeText(p.getNuid()),
            safeText(p.getEmail()),
            safeText(p.getDepartment())
     });
    }
    StudentProfileTable.setModel(model);
}

private void setupTableSelectionListener() {
    StudentProfileTable.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            showSelectedStudentDetails();
        }
    });
}

private String safeText(String value) {
    return value == null ? "" : value;
}

private StudentProfile findStudentProfileByNuid(String nuid) {
    if (business == null || business.getStudentDirectory() == null || nuid == null) {
        return null;
    }

    for (StudentProfile sp : business.getStudentDirectory().getStudentList()) {
        if (sp == null || sp.getPerson() == null) {
            continue;
        }

        String studentNuid = sp.getPerson().getNuid();

        if (studentNuid != null && studentNuid.equals(nuid)) {
            return sp;
        }
    }

    return null;
}

private void showSelectedStudentDetails() {
    int row = StudentProfileTable.getSelectedRow();

    if (row < 0) {
        return;
    }

    String nuid = safeText((String) StudentProfileTable.getValueAt(row, 1));

    StudentProfile selectedStudent = findStudentProfileByNuid(nuid);

    if (selectedStudent != null) {
        txtSelectedStudent.setText(safeText(selectedStudent.getHobbies()));
        txtInterests.setText(safeText(selectedStudent.getInterests()));
    } else {
        txtSelectedStudent.setText("");
        txtInterests.setText("");
    }

    if (business == null || business.getAdvisorRecordDirectory() == null) {
        lblProgressData.setText("Advisor record directory is not available.");
        return;
    }

    AdvisorRecord rec = business.getAdvisorRecordDirectory().findRecordByStudentNuid(nuid);

    if (rec != null) {
        lblProgressData.setText("GPA: " + rec.getGpa()
                + " | Credits: " + rec.getCreditsCompleted() + "/" + rec.getCreditsRequired()
                + " | Standing: " + rec.getAcademicStanding()
                + " | Grad: " + rec.getPotentialGraduationDate());
    } else {
        lblProgressData.setText("No advisor record found.");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentProfileTable = new javax.swing.JTable();
        lblInterests = new javax.swing.JLabel();
        lblSelectedStudentDetails = new javax.swing.JLabel();
        txtSelectedStudent = new javax.swing.JTextField();
        txtInterests = new javax.swing.JTextField();
        lblAcademicProgress = new javax.swing.JLabel();
        lblProgressData = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel1.setText("Manage Student Profiles");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        StudentProfileTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(StudentProfileTable);

        lblInterests.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblInterests.setText("Interests");

        lblSelectedStudentDetails.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblSelectedStudentDetails.setText("Hobbies");

        txtSelectedStudent.setEditable(false);
        txtSelectedStudent.setBackground(new java.awt.Color(204, 204, 204));
        txtSelectedStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSelectedStudentActionPerformed(evt);
            }
        });

        txtInterests.setEditable(false);
        txtInterests.setBackground(new java.awt.Color(204, 204, 204));
        txtInterests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInterestsActionPerformed(evt);
            }
        });

        lblAcademicProgress.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblAcademicProgress.setText("Academic Progress");

        lblProgressData.setText("lblProgressData");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAcademicProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSelectedStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectedStudentDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblInterests, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtInterests, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnBack)
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblProgressData, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInterests)
                    .addComponent(lblSelectedStudentDetails))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtInterests, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(txtSelectedStudent))
                .addGap(28, 28, 28)
                .addComponent(lblAcademicProgress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProgressData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        FacultyWorkAreaJPanel facultyWorkArea = new FacultyWorkAreaJPanel(business, facultyProfile, CardSequencePanel);
        CardSequencePanel.add("FacultyWorkArea", facultyWorkArea);
        java.awt.CardLayout layout = (java.awt.CardLayout) CardSequencePanel.getLayout();
        layout.next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtSelectedStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSelectedStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSelectedStudentActionPerformed

    private void txtInterestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInterestsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInterestsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable StudentProfileTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAcademicProgress;
    private javax.swing.JLabel lblInterests;
    private javax.swing.JLabel lblProgressData;
    private javax.swing.JLabel lblSelectedStudentDetails;
    private javax.swing.JTextField txtInterests;
    private javax.swing.JTextField txtSelectedStudent;
    // End of variables declaration//GEN-END:variables
}
