/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

/**
 *
 * @author abhit
 */
public class PerformanceReports extends javax.swing.JPanel {
    
    private Business.Business business;
    private Business.Profiles.FacultyProfile facultyProfile;
    private javax.swing.JPanel CardSequencePanel;

    /**
     * Creates new form PerformanceReports
     */
    //Initializes the performance report panel with the current business data
    
    public PerformanceReports(Business.Business business, Business.Profiles.FacultyProfile facultyProfile, javax.swing.JPanel CardSequencePanel) {
        this.business= business;
        this.facultyProfile= facultyProfile;
        this.CardSequencePanel= CardSequencePanel;
        initComponents();
        jTable1.setDefaultEditor(Object.class, null);
        populateCourseDropdown();
    populateTable();
    updateStats();
   
    }
    
    //loads unique course numbrts from the grade list into the course dropdown
    private void populateCourseDropdown() {
    StudentPerformanceCombo.removeAllItems();
    java.util.ArrayList<String> seen = new java.util.ArrayList<>();
    for (CourseCatalog.StudentGrade g : business.getGradeList()) {
        if (!seen.contains(g.getCourseNumber())) {
            seen.add(g.getCourseNumber());
            StudentPerformanceCombo.addItem(g.getCourseNumber());
        }
    }
}
//populates the performance table with students and grades for the selected course
private void populateTable() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    String selectedCourse = (String) StudentPerformanceCombo.getSelectedItem();
    if (selectedCourse == null) return;
    for (CourseCatalog.StudentGrade g : business.getGradeList()) {
        if (g.getCourseNumber().equals(selectedCourse)) {
            Object[] row = new Object[4];
            row[0] = g.getStudentName();
            row[1] = g.getNuid();
            row[2] = g.getGrade();
            row[3] = String.format("%.1f", convertGradeToPoints(g.getGrade()));
            model.addRow(row);
        }
    }
}
//Calculates and displays total students enrolled and class average GPA for selected course
private void updateStats() {
    String selectedCourse = (String) StudentPerformanceCombo.getSelectedItem();
    System.out.println("updateStats called, course=" + selectedCourse);
    int count = 0;
    double totalPoints = 0.0;
    for (CourseCatalog.StudentGrade g : business.getGradeList()) {
        if (selectedCourse != null && g.getCourseNumber().equals(selectedCourse)) {
            count++;
            totalPoints += convertGradeToPoints(g.getGrade());
        }
    }
    double avg = (count == 0) ? 0.0 : totalPoints / count;
    System.out.println("count=" + count + " avg=" + avg);

    lblStudentsEnrolled.setText("Students Enrolled " + count);
    lblClassAverage.setText("Class Average (GPA): " + String.format("%.2f", avg));
}
// Converts letter grades into GPA
private double convertGradeToPoints(String grade) {
    if (grade == null) return 0.0;
    switch (grade) {
        case "A":  return 4.0;
        case "A-": return 3.7;
        case "B+": return 3.3;
        case "B":  return 3.0;
        case "B-": return 2.7;
        case "C+": return 2.3;
        case "C":  return 2.0;
        case "D":  return 1.0;
        case "F":  return 0.0;
        default:   return 0.0;
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        StudentPerformanceCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblStudentsEnrolled = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblClassAverage = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        lblTitle.setText("Student Performance Report");

        lblCourse.setText("Course");

        StudentPerformanceCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        StudentPerformanceCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentPerformanceComboActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student", "NUID", "Grade", "Points"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        lblStudentsEnrolled.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        lblStudentsEnrolled.setText("Students Enrolled");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStudentsEnrolled, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStudentsEnrolled, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        lblClassAverage.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        lblClassAverage.setText("Class Average (GPA)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClassAverage, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblClassAverage, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(lblCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(StudentPerformanceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourse)
                    .addComponent(StudentPerformanceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        FacultyWorkAreaJPanel facultyWorkArea = new FacultyWorkAreaJPanel(business, facultyProfile, CardSequencePanel);
        CardSequencePanel.add("FacultyWorkArea", facultyWorkArea);
        java.awt.CardLayout layout = (java.awt.CardLayout) CardSequencePanel.getLayout();
        layout.next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void StudentPerformanceComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentPerformanceComboActionPerformed
        // TODO add your handling code here:
        populateTable();
       updateStats();
    }//GEN-LAST:event_StudentPerformanceComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> StudentPerformanceCombo;
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblClassAverage;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblStudentsEnrolled;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
